[package]
name = "VeToken"
version = "0.0.0"

[addresses]
vetoken =  "0x1"

[dependencies.AptosStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
subdir = "aptos-move/framework/aptos-stdlib"
rev = "mainnet"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
subdir = "aptos-move/framework/aptos-framework"
rev = "mainnet"

[dev-dependencies.TestUtils]
local = "../test_utils/"
