[package]
name = "VeToken"
version = "0.0.0"

[addresses]
vetoken =  "8e4f088757f86e7e9962641ee706085d32395d6a01ca61cb5e59df0e51d12a2b"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
subdir = "aptos-move/framework/aptos-framework"
rev = "mainnet"
